// Hex size for rendering
export const HEX_RADIUS = 38; // radius of hexagon in pixels (smaller = tighter grid)

export type HexState = 'hidden' | 'locked' | 'resource' | 'empty' | 'building' | 'harvester';
export type ResourceType = 'tree' | 'ore' | 'vent' | 'water';
export type Rarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

export interface HexSlotData {
  id: string;           // "d{row}-{col}" e.g. "d4-2" for hub. Old saves: "ring0-0" etc.
  ring: 0 | 1 | 2 | 3; // zone: 0=hub, 1=inner, 2=mid, 3=outer (kept as 'ring' for save compat)
  index: number;        // index within the zone (0-based)
  state: HexState;
  resourceType?: ResourceType;
  rarity?: Rarity;
  yieldPerHour?: number;
  maxCapacity?: number;       // max accumulated units (12h cap)
  lastHarvestedAt?: number;
  buildingType?: string;
  buildingLevel?: number;
  unlockCost?: { minerals: number; volatiles: number; isotopes: number; water?: number };
}

export interface HexPosition {
  id: string;
  ring: number;   // zone 0-3
  index: number;
  row: number;    // diamond row 0-9
  col: number;    // column within the row (0-based)
  x: number;      // pixel x (relative to grid centre)
  y: number;      // pixel y (relative to grid centre)
  zOffset: number; // visual depth offset (mountain effect)
}

// ---------------------------------------------------------------------------
// Diamond layout constants
// ---------------------------------------------------------------------------

// Row widths for 10-row elongated diamond (portrait-optimised)
export const DIAMOND_ROWS = [1, 2, 3, 4, 5, 5, 4, 3, 2, 1] as const;

// Centre hex position
export const CENTER_ROW = 4;
export const CENTER_COL = 2; // col within row 4 (5 hexes wide, hub at index 2)

// ---------------------------------------------------------------------------
// Diamond coordinate helpers
// ---------------------------------------------------------------------------

/**
 * Pre-computed BFS zone lookup table.
 * Zones are assigned by BFS graph distance from the hub hex "d4-2":
 *   zone 0 = hub (dist 0)      — 1 hex
 *   zone 1 = immediate ring    — 5 hexes  (dist 1)
 *   zone 2 = middle ring       — 11 hexes (dist 2)
 *   zone 3 = outer band        — 13 hexes (dist 3+)
 * Total: 30 hexes.
 *
 * Generated by BFS from (4,2) over the adjacency graph of this diamond shape.
 * Using a lookup table avoids recomputing adjacency in the hot path.
 */
const HEX_ZONE_LOOKUP: Record<string, 0 | 1 | 2 | 3> = {
  'd4-2': 0,
  // zone 1 — 5 hexes
  'd4-1': 1, 'd4-3': 1, 'd3-1': 1, 'd3-2': 1, 'd5-2': 1,
  // zone 2 — 11 hexes
  'd4-0': 2, 'd3-0': 2, 'd5-1': 2, 'd4-4': 2, 'd3-3': 2,
  'd5-3': 2, 'd2-0': 2, 'd2-1': 2, 'd2-2': 2, 'd6-1': 2, 'd6-2': 2,
  // zone 3 — 13 hexes
  'd5-0': 3, 'd6-0': 3, 'd5-4': 3, 'd6-3': 3,
  'd1-0': 3, 'd1-1': 3, 'd7-0': 3, 'd7-1': 3, 'd7-2': 3,
  'd0-0': 3, 'd8-0': 3, 'd8-1': 3, 'd9-0': 3,
};

/**
 * Return the zone (0-3) for a diamond hex at (row, col).
 * Uses the pre-computed BFS lookup table for O(1) performance.
 */
export function computeZone(row: number, col: number): 0 | 1 | 2 | 3 {
  const id = `d${row}-${col}`;
  return HEX_ZONE_LOOKUP[id] ?? 3; // default to outer zone for any unlisted hex
}

/**
 * Return pixel position for a diamond hex at (row, col).
 * Pointy-top hex: horizontal spacing = sqrt(3)*size, vertical = 1.5*size.
 * We add a mild gap factor of 1.12 so hexes don't touch.
 */
function diamondToPixel(
  row: number,
  col: number,
  size: number,
): { x: number; y: number } {
  const gap = 1.12;
  const rowWidth = DIAMOND_ROWS[row] ?? 1;
  // Horizontal centre of this hex relative to diamond centre
  const xFrac = col - (rowWidth - 1) / 2;
  const x = xFrac * Math.sqrt(3) * size * gap;
  const y = (row - CENTER_ROW) * 1.5 * size * gap;
  return { x, y };
}

// ---------------------------------------------------------------------------
// Adjacent hex calculation for diamond grid
// ---------------------------------------------------------------------------

/**
 * Get all valid neighbours of (row, col) in the diamond grid.
 * For pointy-top hexes in a rectangular stagger grid the neighbours are:
 *   same row: col-1, col+1
 *   row above: depends on whether the row above is wider or narrower
 *   row below: same logic
 *
 * In our diamond the number of hexes per row changes by ±1 each step.
 * When going from a wider row to a narrower row, the column offset shifts by 0.5.
 * We handle this by projecting the hex's x-fraction onto the neighbour row.
 */
export function getAdjacentIds(row: number, col: number): string[] {
  const neighbours: string[] = [];

  // Same-row neighbours
  const rowWidth = DIAMOND_ROWS[row] ?? 0;
  if (col > 0) neighbours.push(`d${row}-${col - 1}`);
  if (col < rowWidth - 1) neighbours.push(`d${row}-${col + 1}`);

  // x-fraction of current hex (centre-relative)
  const xFrac = col - (rowWidth - 1) / 2;

  // Helper: find column in a target row whose x-fraction is nearest to xFrac
  const neighboursInRow = (targetRow: number, xFracSelf: number, deltaX: number = 0) => {
    if (targetRow < 0 || targetRow >= DIAMOND_ROWS.length) return;
    const tw = DIAMOND_ROWS[targetRow];
    // Two candidate columns (hex grid step is 0.5 per row when width changes)
    const targetXFrac = xFracSelf + deltaX;
    const candidates = [Math.floor(targetXFrac + (tw - 1) / 2), Math.ceil(targetXFrac + (tw - 1) / 2)];
    const seen = new Set<number>();
    for (const c of candidates) {
      if (c >= 0 && c < tw && !seen.has(c)) {
        seen.add(c);
        neighbours.push(`d${targetRow}-${c}`);
      }
    }
  };

  // Row above: when moving up, x-fraction shifts by ±0.5 depending on width change
  if (row > 0) {
    const aboveWidth = DIAMOND_ROWS[row - 1];
    if (aboveWidth > rowWidth) {
      // wider above: two upper neighbours
      neighboursInRow(row - 1, xFrac, 0.5);
      neighboursInRow(row - 1, xFrac, -0.5);
    } else if (aboveWidth < rowWidth) {
      // narrower above: project straight
      neighboursInRow(row - 1, xFrac, 0);
    } else {
      // same width: straight + maybe offset
      neighboursInRow(row - 1, xFrac, 0);
    }
  }

  // Row below: symmetric
  if (row < DIAMOND_ROWS.length - 1) {
    const belowWidth = DIAMOND_ROWS[row + 1];
    if (belowWidth > rowWidth) {
      neighboursInRow(row + 1, xFrac, 0.5);
      neighboursInRow(row + 1, xFrac, -0.5);
    } else if (belowWidth < rowWidth) {
      neighboursInRow(row + 1, xFrac, 0);
    } else {
      neighboursInRow(row + 1, xFrac, 0);
    }
  }

  // Deduplicate and filter valid ids
  const all = new Set(neighbours);
  return Array.from(all).filter((id) => {
    const m = id.match(/^d(\d+)-(\d+)$/);
    if (!m) return false;
    const r = parseInt(m[1], 10);
    const c = parseInt(m[2], 10);
    return r >= 0 && r < DIAMOND_ROWS.length && c >= 0 && c < (DIAMOND_ROWS[r] ?? 0);
  });
}

// ---------------------------------------------------------------------------
// Diamond position list (30 hexes)
// ---------------------------------------------------------------------------

interface DiamondHex {
  row: number;
  col: number;
  id: string;
  zone: 0 | 1 | 2 | 3;
}

function buildDiamondHexes(): DiamondHex[] {
  const hexes: DiamondHex[] = [];
  for (let row = 0; row < DIAMOND_ROWS.length; row++) {
    const width = DIAMOND_ROWS[row];
    for (let col = 0; col < width; col++) {
      const zone = computeZone(row, col);
      hexes.push({ row, col, id: `d${row}-${col}`, zone });
    }
  }
  return hexes;
}

/** Generate all 30 diamond hex positions */
export function getHexPositions(): HexPosition[] {
  const hexes = buildDiamondHexes();

  // Pre-count zone indices
  const zoneCounters: Record<number, number> = { 0: 0, 1: 0, 2: 0, 3: 0 };

  return hexes.map(({ row, col, id, zone }) => {
    const { x, y } = diamondToPixel(row, col, HEX_RADIUS);
    const zOffset = Math.abs(row - CENTER_ROW) * 2;
    const index = zoneCounters[zone]++;
    return { id, ring: zone, index, row, col, x, y, zOffset };
  });
}

/** SVG polygon points string for a pointy-top hexagon */
export function hexPoints(cx: number, cy: number, r: number): string {
  const pts: string[] = [];
  for (let i = 0; i < 6; i++) {
    const angle = (60 * i - 90) * Math.PI / 180; // pointy-top: start at -90 deg (top vertex)
    pts.push(`${cx + r * Math.cos(angle)},${cy + r * Math.sin(angle)}`);
  }
  return pts.join(' ');
}

/** CSS clip-path for a pointy-top hexagon */
export const HEX_CLIP_PATH = 'polygon(50% 0%, 93.3% 25%, 93.3% 75%, 50% 100%, 6.7% 75%, 6.7% 25%)';

// ---------------------------------------------------------------------------
// Rarity + resource generation (seeded, deterministic)
// ---------------------------------------------------------------------------

export function rollRarity(seed: number, slotId: string): Rarity {
  const h = Math.abs(Math.sin(seed * 0.1 + hashStr(slotId) * 0.01)) * 100;
  if (h < 2) return 'legendary';
  if (h < 10) return 'epic';
  if (h < 25) return 'rare';
  if (h < 50) return 'uncommon';
  return 'common';
}

export function rarityYield(rarity: Rarity): number {
  switch (rarity) {
    case 'legendary': return 9 + Math.floor(Math.random() * 2);
    case 'epic':      return 7 + Math.floor(Math.random() * 2);
    case 'rare':      return 5 + Math.floor(Math.random() * 2);
    case 'uncommon':  return 3 + Math.floor(Math.random() * 2);
    default:          return 1 + Math.floor(Math.random() * 2);
  }
}

/** Max capacity = 12 hours of yield */
export function rarityMaxCapacity(yieldPerHour: number): number {
  return yieldPerHour * 12;
}

export const RARITY_COLORS: Record<Rarity, string> = {
  common:    '#94a3b8',
  uncommon:  '#44ff88',
  rare:      '#4488ff',
  epic:      '#aa66ff',
  legendary: '#ffcc44',
};

export const RESOURCE_COLORS: Record<ResourceType, string> = {
  tree:  '#22c55e',
  ore:   '#a0845e',
  vent:  '#22d3ee',
  water: '#3b82f6',
};

// ---------------------------------------------------------------------------
// Zone unlock costs
// ---------------------------------------------------------------------------

/**
 * Progressive unlock cost for diamond zones.
 * Zone 1: isotopes only (6 steps)
 * Zone 2: minerals + volatiles (12 steps)
 * Zone 3: minerals + volatiles + water (11 steps)
 *
 * @param zone        — 1, 2, or 3
 * @param unlockOrder — how many slots in this zone have been unlocked already (0-based)
 */
export function getUnlockCost(
  zone: number,
  unlockOrder: number = 0,
): { minerals: number; volatiles: number; isotopes: number; water?: number } {
  if (zone === 1) {
    const table = [
      { minerals: 0, volatiles: 0, isotopes: 5  },
      { minerals: 0, volatiles: 0, isotopes: 8  },
      { minerals: 0, volatiles: 0, isotopes: 12 },
      { minerals: 0, volatiles: 0, isotopes: 16 },
      { minerals: 0, volatiles: 0, isotopes: 21 },
      { minerals: 0, volatiles: 0, isotopes: 28 },
    ];
    return { ...table[Math.min(unlockOrder, table.length - 1)] };
  }

  if (zone === 2) {
    const table = [
      { minerals: 8,  volatiles: 5,  isotopes: 0 },
      { minerals: 12, volatiles: 8,  isotopes: 0 },
      { minerals: 16, volatiles: 11, isotopes: 0 },
      { minerals: 22, volatiles: 14, isotopes: 0 },
      { minerals: 28, volatiles: 18, isotopes: 0 },
      { minerals: 35, volatiles: 22, isotopes: 0 },
      { minerals: 42, volatiles: 27, isotopes: 0 },
      { minerals: 50, volatiles: 32, isotopes: 0 },
      { minerals: 58, volatiles: 37, isotopes: 0 },
      { minerals: 68, volatiles: 43, isotopes: 0 },
      { minerals: 78, volatiles: 50, isotopes: 0 },
      { minerals: 90, volatiles: 57, isotopes: 0 },
    ];
    return { ...table[Math.min(unlockOrder, table.length - 1)] };
  }

  // Zone 3: minerals + volatiles + water
  const table = [
    { minerals: 30, volatiles: 20, isotopes: 0, water: 10 },
    { minerals: 40, volatiles: 25, isotopes: 0, water: 12 },
    { minerals: 52, volatiles: 32, isotopes: 0, water: 15 },
    { minerals: 65, volatiles: 40, isotopes: 0, water: 18 },
    { minerals: 80, volatiles: 50, isotopes: 0, water: 22 },
    { minerals: 98, volatiles: 61, isotopes: 0, water: 26 },
    { minerals: 118, volatiles: 74, isotopes: 0, water: 31 },
    { minerals: 140, volatiles: 88, isotopes: 0, water: 37 },
    { minerals: 165, volatiles: 103, isotopes: 0, water: 44 },
    { minerals: 192, volatiles: 120, isotopes: 0, water: 52 },
    { minerals: 222, volatiles: 139, isotopes: 0, water: 61 },
  ];
  return { ...table[Math.min(unlockOrder, table.length - 1)] };
}

// ---------------------------------------------------------------------------
// Resource rolling with geographic bias
// ---------------------------------------------------------------------------

/**
 * Roll resource type for a diamond hex with geographic bias.
 * Top rows (0-2): +tree (isotopes)
 * Bottom rows (7-9): +ore (minerals)
 * Edge columns (first or last in row): +water
 * Center area: balanced / +vent
 */
export function rollResourceType(
  seed: number,
  slotId: string,
  row?: number,
  col?: number,
): ResourceType {
  const h = Math.abs(Math.sin(seed * 0.3 + hashStr(slotId) * 0.07)) * 100;

  // Parse row/col from id if not provided
  let r = row;
  let c = col;
  if (r === undefined || c === undefined) {
    const m = slotId.match(/^d(\d+)-(\d+)$/);
    if (m) {
      r = parseInt(m[1], 10);
      c = parseInt(m[2], 10);
    }
  }

  if (r !== undefined && c !== undefined) {
    const rowWidth = DIAMOND_ROWS[r] ?? 1;
    const isEdgeCol = c === 0 || c === rowWidth - 1;
    const isTopArea = r <= 2;
    const isBottomArea = r >= 7;

    // Edge columns: strong water bias
    if (isEdgeCol) {
      if (h < 50) return 'water';
      if (h < 70) return 'vent';
      if (h < 85) return 'tree';
      return 'ore';
    }
    // Top rows: tree bias
    if (isTopArea) {
      if (h < 50) return 'tree';
      if (h < 70) return 'ore';
      if (h < 85) return 'vent';
      return 'water';
    }
    // Bottom rows: ore bias
    if (isBottomArea) {
      if (h < 50) return 'ore';
      if (h < 70) return 'tree';
      if (h < 85) return 'vent';
      return 'water';
    }
  }

  // Center / default: balanced with slight vent bias
  if (h < 30) return 'tree';
  if (h < 55) return 'ore';
  if (h < 80) return 'vent';
  return 'water';
}

function hashStr(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = ((h << 5) - h + s.charCodeAt(i)) | 0;
  return h;
}

// ---------------------------------------------------------------------------
// Respawn + harvest math
// ---------------------------------------------------------------------------

export const RESOURCE_RESPAWN_MS = 3_600_000; // 1 hour

/** Calculate how many units have accumulated since last harvest (capped at maxCapacity) */
export function getAccumulatedYield(
  lastHarvestedAt: number | undefined,
  yieldPerHour: number,
  maxCapacity: number,
): number {
  if (!lastHarvestedAt) return yieldPerHour; // first harvest = 1 hour worth
  const elapsedHours = (Date.now() - lastHarvestedAt) / RESOURCE_RESPAWN_MS;
  return Math.min(maxCapacity, Math.floor(elapsedHours * yieldPerHour));
}

/** Check if at least 1 unit has accumulated */
export function isResourceReady(lastHarvestedAt: number | undefined, yieldPerHour: number = 1): boolean {
  if (!lastHarvestedAt) return true;
  const elapsedMs = Date.now() - lastHarvestedAt;
  const msPerUnit = RESOURCE_RESPAWN_MS / yieldPerHour;
  return elapsedMs >= msPerUnit;
}

/** Time remaining until next unit (ms) */
export function respawnTimeRemaining(lastHarvestedAt: number, yieldPerHour: number = 1): number {
  const msPerUnit = RESOURCE_RESPAWN_MS / yieldPerHour;
  return Math.max(0, msPerUnit - (Date.now() - lastHarvestedAt));
}

// ---------------------------------------------------------------------------
// Legacy ring adjacency (kept for backward-compat references)
// ---------------------------------------------------------------------------

/** @deprecated Use getAdjacentIds() with diamond coordinates instead */
export function getAdjacentRing2Indices(ring1Index: number): number[] {
  return [ring1Index * 2, (ring1Index * 2 + 1) % 12];
}
