export { ELEMENTS, EARTH_CRUST_COMPOSITION, EARTH_BULK_COMPOSITION, EARTH_ATMOSPHERE, VENUS_ATMOSPHERE, MARS_ATMOSPHERE, TITAN_ATMOSPHERE, SOLAR_ABUNDANCE, ROCKY_PLANET_COMPOSITION, ICE_RICH_COMPOSITION } from './elements.js';
export type { Element, ElementCategory } from './elements.js';
export { generateAtmosphere } from './atmosphere.js';
export type { Atmosphere, PlanetZone } from './atmosphere.js';
export { generateResources } from './minerals.js';
export type { MineralDeposit, PlanetResources, TotalResources } from './minerals.js';
export { generateHydrosphere } from './water.js';
export type { Hydrosphere } from './water.js';
export { ELEMENT_GROUP, GROUP_NAMES, GROUP_COLORS, RESOURCE_GROUPS, computeGroupTotals, getGroupElements } from './resource-groups.js';
export type { ResourceGroup } from './resource-groups.js';
