// Audio generation pipeline for Encyclopedia lessons.
//
// Calls the deployed `/api/academy-library/generate-tts` endpoint (which has
// access to GOOGLE_PRIVATE_KEY since that env var is `Sensitive` in Vercel
// and isn't exported via `vercel env pull`).
//
// Usage:
//   BUILD_API_KEY=<key> npx tsx scripts/encyclopedia-tts.ts
//   BUILD_API_KEY=<key> npx tsx scripts/encyclopedia-tts.ts --slug black-holes-intro
//   BUILD_API_KEY=<key> npx tsx scripts/encyclopedia-tts.ts --base http://localhost:3000

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { Lesson, AssetsManifest, Language, LessonAssets } from '../packages/client/src/encyclopedia/types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');
const CONTENT_DIR = join(ROOT, 'packages/client/src/encyclopedia/content');
const MANIFEST_PATH = join(ROOT, 'packages/client/src/encyclopedia/assets-manifest.json');

interface BuildOptions {
  baseUrl: string;
  slug?: string;
  force: boolean;
  apiKey: string;
}

function parseArgs(): BuildOptions {
  const args = process.argv.slice(2);
  const opts: BuildOptions = {
    baseUrl: 'https://nebulife.space',
    force: false,
    apiKey: process.env.BUILD_API_KEY ?? '',
  };
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--base') opts.baseUrl = args[++i];
    else if (arg === '--slug') opts.slug = args[++i];
    else if (arg === '--force') opts.force = true;
  }
  if (!opts.apiKey) {
    throw new Error('BUILD_API_KEY env var is required');
  }
  return opts;
}

function findLessonFiles(): string[] {
  const files: string[] = [];
  function walk(dir: string) {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      const st = statSync(full);
      if (st.isDirectory()) walk(full);
      else if (entry.endsWith('.uk.ts') || entry.endsWith('.en.ts')) files.push(full);
    }
  }
  walk(CONTENT_DIR);
  return files.sort();
}

async function loadLesson(filePath: string): Promise<Lesson> {
  const url = pathToFileURL(filePath).href;
  const mod = await import(url);
  return mod.default as Lesson;
}

function loadManifest(): AssetsManifest {
  try {
    const raw = readFileSync(MANIFEST_PATH, 'utf-8');
    const data = JSON.parse(raw);
    return (data.lessons ?? {}) as AssetsManifest;
  } catch {
    return {};
  }
}

function saveManifest(manifest: AssetsManifest) {
  const wrapped = {
    _comment: 'Generated by scripts/encyclopedia-build.ts. Do not edit manually.',
    _format: 'Map of slug -> { images: { cacheKey: url }, audio: { lang: { female, male, durationSec } } }',
    _generatedAt: new Date().toISOString(),
    lessons: manifest,
  };
  writeFileSync(MANIFEST_PATH, JSON.stringify(wrapped, null, 2) + '\n', 'utf-8');
}

/** Plain-text body for TTS. */
function buildSpokenText(lesson: Lesson): string {
  const parts: string[] = [];
  parts.push(lesson.title + '.');
  parts.push(lesson.subtitle);
  for (const block of lesson.body) {
    if (block.heading) parts.push(block.heading + '.');
    if (block.paragraphs) {
      for (const p of block.paragraphs) {
        const clean = p.replace(/\*\*(.*?)\*\*/g, '$1').replace(/_(.+?)_/g, '$1');
        parts.push(clean);
      }
    }
    if (block.image?.caption) parts.push(block.image.caption);
    if (block.diagram?.caption) parts.push(block.diagram.caption);
  }
  return parts.join('\n\n');
}

async function callTtsEndpoint(
  baseUrl: string,
  apiKey: string,
  slug: string,
  language: Language,
  gender: 'female' | 'male',
  text: string,
): Promise<{ url: string; voiceName: string; durationSec: number }> {
  const res = await fetch(`${baseUrl}/api/academy-library/generate-tts`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-academy-build-key': apiKey,
    },
    body: JSON.stringify({
      slug,
      language,
      gender,
      text,
      provider: 'gemini',
      voiceName: gender === 'female' ? 'Kore' : 'Charon',
    }),
  });
  const data = await res.json();
  if (!res.ok) {
    throw new Error(`HTTP ${res.status}: ${JSON.stringify(data)}`);
  }
  return data as { url: string; voiceName: string; durationSec: number };
}

async function main() {
  const opts = parseArgs();
  console.log('Encyclopedia TTS build');
  console.log('  baseUrl:', opts.baseUrl);
  console.log('  slug:', opts.slug ?? '(all)');

  const files = findLessonFiles().filter((f) => !opts.slug || f.includes(opts.slug));
  console.log(`Found ${files.length} lesson files`);

  const manifest = loadManifest();

  for (const file of files) {
    const lesson = await loadLesson(file);
    console.log(`\n[${lesson.slug}.${lesson.language}] ${lesson.title}`);

    const existing: LessonAssets = manifest[lesson.slug] ?? {
      images: {},
      audio: {
        uk: { female: '', male: '', durationSec: 0 },
        en: { female: '', male: '', durationSec: 0 },
      },
    };
    const audio = { ...(existing.audio ?? {}) } as LessonAssets['audio'];
    const lang: Language = lesson.language;
    const langAudio = audio[lang] ?? { female: '', male: '', durationSec: 0 };

    const text = buildSpokenText(lesson);
    console.log(`  text length: ${text.length} chars`);

    for (const gender of ['female', 'male'] as const) {
      if (!opts.force && langAudio[gender]) {
        console.log(`  ✓ audio ${lang}.${gender} (cached)`);
        continue;
      }
      console.log(`  → audio ${lang}.${gender} ...`);
      try {
        const result = await callTtsEndpoint(opts.baseUrl, opts.apiKey, lesson.slug, lang, gender, text);
        langAudio[gender] = result.url;
        langAudio.durationSec = result.durationSec;
        console.log(`    ${result.url} (${result.durationSec}s, voice: ${result.voiceName})`);
      } catch (err) {
        console.error(`    FAILED: ${err instanceof Error ? err.message : String(err)}`);
      }
    }

    audio[lang] = langAudio;
    manifest[lesson.slug] = { ...existing, audio };
    saveManifest(manifest);
  }

  console.log(`\nDone. Manifest written to ${MANIFEST_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
