// Encyclopedia asset-generation pipeline.
//
// Scans all lesson modules under
//   packages/client/src/encyclopedia/content/**/*.{uk,en}.ts
// and generates:
//   - Hero + inline images via Gemini Imagen → Vercel Blob
//   - TTS audio (female + male, uk + en) via Google Cloud TTS → Vercel Blob
// Results are written to:
//   packages/client/src/encyclopedia/assets-manifest.json
//
// Usage:
//   npx tsx scripts/encyclopedia-build.ts                    # incremental
//   npx tsx scripts/encyclopedia-build.ts --force            # regenerate all
//   npx tsx scripts/encyclopedia-build.ts --slug black-holes-intro   # single lesson
//   npx tsx scripts/encyclopedia-build.ts --no-tts           # skip audio
//   npx tsx scripts/encyclopedia-build.ts --no-images        # skip images

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { put } from '@vercel/blob';

// Manual .env loader — handles multi-line values (PEM keys) properly,
// unlike `source` in bash which chokes on newlines inside quoted values.
function loadDotEnv(path: string): void {
  if (!existsSync(path)) return;
  const text = readFileSync(path, 'utf-8');
  const re = /^([A-Z_][A-Z0-9_]*)=(?:"((?:[^"\\]|\\.)*)"|'([^']*)'|(.*?))\s*$/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    const key = m[1];
    const raw = m[2] ?? m[3] ?? m[4] ?? '';
    // Unescape \n inside double-quoted values
    const value = m[2] !== undefined ? raw.replace(/\\n/g, '\n').replace(/\\"/g, '"') : raw;
    if (process.env[key] === undefined) process.env[key] = value;
  }
}
// Load .env.production.local first (preferred for build), then .env.local fallback
const ROOT_PATH = resolve(dirname(fileURLToPath(import.meta.url)), '..');
loadDotEnv(join(ROOT_PATH, '.env.production.local'));
loadDotEnv(join(ROOT_PATH, '.env.local'));
import { generateImageWithGemini } from '../packages/server/src/gemini-client.js';
import { synthesizeLongText } from '../packages/server/src/google-tts-client.js';
import type { Lesson, AssetsManifest, LessonAssets, Language } from '../packages/client/src/encyclopedia/types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');
const CONTENT_DIR = join(ROOT, 'packages/client/src/encyclopedia/content');
const MANIFEST_PATH = join(ROOT, 'packages/client/src/encyclopedia/assets-manifest.json');

interface BuildOptions {
  force: boolean;
  slug?: string;
  noTts: boolean;
  noImages: boolean;
}

function parseArgs(): BuildOptions {
  const args = process.argv.slice(2);
  const opts: BuildOptions = { force: false, noTts: false, noImages: false };
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--force') opts.force = true;
    else if (arg === '--slug') opts.slug = args[++i];
    else if (arg === '--no-tts') opts.noTts = true;
    else if (arg === '--no-images') opts.noImages = true;
  }
  return opts;
}

function findLessonFiles(): string[] {
  const files: string[] = [];
  function walk(dir: string) {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      const st = statSync(full);
      if (st.isDirectory()) walk(full);
      else if (entry.endsWith('.uk.ts') || entry.endsWith('.en.ts')) files.push(full);
    }
  }
  walk(CONTENT_DIR);
  return files.sort();
}

async function loadLesson(filePath: string): Promise<Lesson> {
  const url = pathToFileURL(filePath).href;
  const mod = await import(url);
  return mod.default as Lesson;
}

function loadManifest(): AssetsManifest {
  try {
    const raw = readFileSync(MANIFEST_PATH, 'utf-8');
    const data = JSON.parse(raw);
    // Manifest is wrapped in { lessons: {...} } for readability — unwrap
    return (data.lessons ?? {}) as AssetsManifest;
  } catch {
    return {};
  }
}

function saveManifest(manifest: AssetsManifest) {
  const wrapped = {
    _comment: 'Generated by scripts/encyclopedia-build.ts. Do not edit manually.',
    _format: 'Map of slug -> { images: { cacheKey: url }, audio: { lang: { female, male, durationSec } } }',
    _generatedAt: new Date().toISOString(),
    lessons: manifest,
  };
  writeFileSync(MANIFEST_PATH, JSON.stringify(wrapped, null, 2) + '\n', 'utf-8');
}

/** Upload arbitrary bytes to Vercel Blob and return public URL. */
async function uploadBlob(filename: string, bytes: Buffer | Uint8Array, contentType: string): Promise<string> {
  const blob = await put(`academy/${filename}`, Buffer.from(bytes), {
    access: 'public',
    contentType,
    addRandomSuffix: false,
    allowOverwrite: true,
  });
  return blob.url;
}

/** Plain-text body for TTS — concatenates title, subtitle, and all paragraphs. */
function buildSpokenText(lesson: Lesson): string {
  const parts: string[] = [];
  parts.push(lesson.title + '.');
  parts.push(lesson.subtitle);
  for (const block of lesson.body) {
    if (block.heading) parts.push(block.heading + '.');
    if (block.paragraphs) {
      for (const p of block.paragraphs) {
        // Strip markdown emphasis markers for natural speech
        const clean = p.replace(/\*\*(.*?)\*\*/g, '$1').replace(/_(.+?)_/g, '$1');
        parts.push(clean);
      }
    }
    if (block.image?.caption) parts.push(block.image.caption);
    if (block.diagram?.caption) parts.push(block.diagram.caption);
  }
  return parts.join('\n\n');
}

async function generateLessonImages(
  lesson: Lesson,
  existing: LessonAssets,
  opts: BuildOptions,
): Promise<LessonAssets> {
  const images = { ...existing.images };
  const allImages = [lesson.hero, ...lesson.body.flatMap((b) => (b.image ? [b.image] : []))];

  for (const img of allImages) {
    if (!opts.force && images[img.cacheKey]) {
      console.log(`  ✓ image ${img.cacheKey} (cached)`);
      continue;
    }
    console.log(`  → image ${img.cacheKey} ...`);
    try {
      const result = await generateImageWithGemini({
        prompt: img.prompt,
        aspectRatio: img.aspectRatio ?? '16:9',
      });
      images[img.cacheKey] = result.imageUrl;
      console.log(`    ${result.imageUrl}`);
    } catch (err) {
      console.error(`    FAILED: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  return { ...existing, images };
}

async function generateLessonAudio(
  lesson: Lesson,
  existing: LessonAssets,
  opts: BuildOptions,
): Promise<LessonAssets> {
  const lang: Language = lesson.language;
  const langCode = lang === 'uk' ? 'uk-UA' : 'en-US';
  const text = buildSpokenText(lesson);

  const existingForLang = existing.audio?.[lang];
  const audio: typeof existing.audio = { ...existing.audio } as typeof existing.audio;

  const needsFemale = opts.force || !existingForLang?.female;
  const needsMale = opts.force || !existingForLang?.male;

  if (!needsFemale && !needsMale) {
    console.log(`  ✓ audio ${lang} (cached)`);
    return { ...existing, audio };
  }

  let durationSec = existingForLang?.durationSec ?? 0;
  let female = existingForLang?.female ?? '';
  let male = existingForLang?.male ?? '';

  if (needsFemale) {
    console.log(`  → audio ${lang} female ...`);
    const res = await synthesizeLongText({ text, language: langCode, gender: 'female' });
    female = await uploadBlob(`audio/${lesson.slug}.${lang}.female.mp3`, res.audio, 'audio/mpeg');
    durationSec = res.durationSec;
    console.log(`    ${female} (${durationSec}s, voice: ${res.voiceName})`);
  }

  if (needsMale) {
    console.log(`  → audio ${lang} male ...`);
    const res = await synthesizeLongText({ text, language: langCode, gender: 'male' });
    male = await uploadBlob(`audio/${lesson.slug}.${lang}.male.mp3`, res.audio, 'audio/mpeg');
    if (!durationSec) durationSec = res.durationSec;
    console.log(`    ${male} (${res.durationSec}s, voice: ${res.voiceName})`);
  }

  audio[lang] = { female, male, durationSec };
  return { ...existing, audio };
}

async function main() {
  const opts = parseArgs();
  console.log('Encyclopedia asset build');
  console.log('  options:', opts);

  // Sanity check env
  if (!process.env.GEMINI_API_KEY && !opts.noImages) {
    throw new Error('GEMINI_API_KEY is not set. Run `vercel env pull` or pass --no-images');
  }
  if (!process.env.GOOGLE_PRIVATE_KEY && !opts.noTts) {
    throw new Error('GOOGLE_PRIVATE_KEY is not set. Run `vercel env pull` or pass --no-tts');
  }
  if (!process.env.BLOB_READ_WRITE_TOKEN) {
    throw new Error('BLOB_READ_WRITE_TOKEN is not set. Run `vercel env pull`');
  }

  const files = findLessonFiles().filter((f) => !opts.slug || f.includes(opts.slug));
  console.log(`Found ${files.length} lesson files`);

  const manifest = loadManifest();

  for (const file of files) {
    const lesson = await loadLesson(file);
    console.log(`\n[${lesson.slug}.${lesson.language}] ${lesson.title}`);

    const existing: LessonAssets = manifest[lesson.slug] ?? {
      images: {},
      audio: { uk: { female: '', male: '', durationSec: 0 }, en: { female: '', male: '', durationSec: 0 } },
    };

    let updated = existing;
    if (!opts.noImages) updated = await generateLessonImages(lesson, updated, opts);
    if (!opts.noTts) updated = await generateLessonAudio(lesson, updated, opts);

    manifest[lesson.slug] = updated;
    saveManifest(manifest); // Save after each lesson to checkpoint progress
  }

  console.log(`\nDone. Manifest written to ${MANIFEST_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
