// Audio generation pipeline for Encyclopedia lessons.
//
// Calls the deployed `/api/academy-library/generate-tts` endpoint (which has
// access to GOOGLE_PRIVATE_KEY since that env var is `Sensitive` in Vercel
// and isn't exported via `vercel env pull`).
//
// Usage:
//   BUILD_API_KEY=<key> npx tsx scripts/encyclopedia-tts.ts
//   BUILD_API_KEY=<key> npx tsx scripts/encyclopedia-tts.ts --slug black-holes-intro
//   BUILD_API_KEY=<key> npx tsx scripts/encyclopedia-tts.ts --base http://localhost:3000

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { Lesson, AssetsManifest, Language, LessonAssets } from '../packages/client/src/encyclopedia/types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');
const CONTENT_DIR = join(ROOT, 'packages/client/src/encyclopedia/content');
const MANIFEST_PATH = join(ROOT, 'packages/client/src/encyclopedia/assets-manifest.json');

interface BuildOptions {
  baseUrl: string;
  slug?: string;
  force: boolean;
  apiKey: string;
}

function parseArgs(): BuildOptions {
  const args = process.argv.slice(2);
  const opts: BuildOptions = {
    baseUrl: 'https://nebulife.space',
    force: false,
    apiKey: process.env.BUILD_API_KEY ?? '',
  };
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--base') opts.baseUrl = args[++i];
    else if (arg === '--slug') opts.slug = args[++i];
    else if (arg === '--force') opts.force = true;
  }
  if (!opts.apiKey) {
    throw new Error('BUILD_API_KEY env var is required');
  }
  return opts;
}

function findLessonFiles(): string[] {
  const files: string[] = [];
  function walk(dir: string) {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      const st = statSync(full);
      if (st.isDirectory()) walk(full);
      else if (entry.endsWith('.uk.ts') || entry.endsWith('.en.ts')) files.push(full);
    }
  }
  walk(CONTENT_DIR);
  return files.sort();
}

async function loadLesson(filePath: string): Promise<Lesson> {
  const url = pathToFileURL(filePath).href;
  const mod = await import(url);
  return mod.default as Lesson;
}

function loadManifest(): AssetsManifest {
  try {
    const raw = readFileSync(MANIFEST_PATH, 'utf-8');
    const data = JSON.parse(raw);
    return (data.lessons ?? {}) as AssetsManifest;
  } catch {
    return {};
  }
}

function saveManifest(manifest: AssetsManifest) {
  const wrapped = {
    _comment: 'Generated by scripts/encyclopedia-build.ts. Do not edit manually.',
    _format: 'Map of slug -> { images: { cacheKey: url }, audio: { lang: { female, male, durationSec } } }',
    _generatedAt: new Date().toISOString(),
    lessons: manifest,
  };
  writeFileSync(MANIFEST_PATH, JSON.stringify(wrapped, null, 2) + '\n', 'utf-8');
}

// ── Ukrainian number spell-out for TTS pre-processing ───────────────────────
// ElevenLabs reads bare 4-digit years (e.g. "1946") oddly in Ukrainian. Pre-
// processing them into the genitive ordinal form ("тисяча дев'ятсот сорок
// шостого") matches the most common attribution context in our prose
// ("у 1946 році", "1929 року", "(1965)") and is grammatically reasonable
// even when the surrounding case differs slightly.
const UA_HUNDREDS_CARDINAL: Record<number, string> = {
  100: 'сто', 200: 'двісті', 300: 'триста', 400: 'чотириста',
  500: "п'ятсот", 600: 'шістсот', 700: 'сімсот',
  800: 'вісімсот', 900: "дев'ятсот",
};
const UA_HUNDREDS_GENITIVE: Record<number, string> = {
  100: 'сотого', 200: 'двохсотого', 300: 'трьохсотого', 400: 'чотирьохсотого',
  500: "п'ятисотого", 600: 'шестисотого', 700: 'семисотого',
  800: 'восьмисотого', 900: "дев'ятисотого",
};
const UA_TENS_CARDINAL: Record<number, string> = {
  20: 'двадцять', 30: 'тридцять', 40: 'сорок',
  50: "п'ятдесят", 60: 'шістдесят', 70: 'сімдесят',
  80: "вісімдесят", 90: "дев'яносто",
};
const UA_TENS_GENITIVE: Record<number, string> = {
  20: 'двадцятого', 30: 'тридцятого', 40: 'сорокового',
  50: "п'ятдесятого", 60: 'шістдесятого', 70: 'сімдесятого',
  80: 'вісімдесятого', 90: "дев'яностого",
};
const UA_ONES_GENITIVE = ['', 'першого', 'другого', 'третього', 'четвертого',
  "п'ятого", 'шостого', 'сьомого', 'восьмого', "дев'ятого"];
const UA_TEENS_GENITIVE: Record<number, string> = {
  10: 'десятого', 11: 'одинадцятого', 12: 'дванадцятого', 13: 'тринадцятого',
  14: 'чотирнадцятого', 15: "п'ятнадцятого", 16: 'шістнадцятого',
  17: 'сімнадцятого', 18: 'вісімнадцятого', 19: "дев'ятнадцятого",
};

function spellOutUkrainianYear(year: number): string {
  if (year < 1000 || year > 2099) return String(year);
  const isTwoThousand = year >= 2000;
  const thousand = isTwoThousand ? 'дві тисячі' : 'тисяча';
  const remainder = year - (isTwoThousand ? 2000 : 1000);
  const hundreds = Math.floor(remainder / 100) * 100;
  const lastTwo = remainder % 100;
  const tens = Math.floor(lastTwo / 10) * 10;
  const ones = lastTwo % 10;

  const parts: string[] = [];
  // Final-word position determines genitive ending. We add cardinal forms
  // for non-final positions, genitive for the final.
  if (lastTwo === 0 && hundreds === 0) {
    return isTwoThousand ? 'двохтисячного' : 'тисячного';
  }
  parts.push(thousand);
  if (lastTwo === 0) {
    parts.push(UA_HUNDREDS_GENITIVE[hundreds]);
    return parts.join(' ');
  }
  if (hundreds > 0) parts.push(UA_HUNDREDS_CARDINAL[hundreds]);
  if (lastTwo >= 10 && lastTwo <= 19) {
    parts.push(UA_TEENS_GENITIVE[lastTwo]);
  } else if (ones === 0) {
    parts.push(UA_TENS_GENITIVE[tens]);
  } else if (tens === 0) {
    parts.push(UA_ONES_GENITIVE[ones]);
  } else {
    parts.push(UA_TENS_CARDINAL[tens]);
    parts.push(UA_ONES_GENITIVE[ones]);
  }
  return parts.join(' ');
}

/** Pre-process Ukrainian spoken text: replace bare years with spelled-out form. */
function preprocessUkrainianForTts(text: string): string {
  return text.replace(/\b(1[0-9]{3}|20[0-9]{2})\b/g, (m) => spellOutUkrainianYear(parseInt(m, 10)));
}

/** Plain-text body for TTS. */
function buildSpokenText(lesson: Lesson): string {
  const parts: string[] = [];
  parts.push(lesson.title + '.');
  parts.push(lesson.subtitle);
  for (const block of lesson.body) {
    if (block.heading) parts.push(block.heading + '.');
    if (block.paragraphs) {
      for (const p of block.paragraphs) {
        const clean = p.replace(/\*\*(.*?)\*\*/g, '$1').replace(/_(.+?)_/g, '$1');
        parts.push(clean);
      }
    }
    if (block.image?.caption) parts.push(block.image.caption);
    if (block.diagram?.caption) parts.push(block.diagram.caption);
  }
  let result = parts.join('\n\n');
  // For Ukrainian lessons, swap bare years for genitive spelled-out form so
  // ElevenLabs reads them naturally in attribution contexts.
  if (lesson.language === 'uk') result = preprocessUkrainianForTts(result);
  return result;
}

async function callTtsEndpoint(
  baseUrl: string,
  apiKey: string,
  slug: string,
  language: Language,
  text: string,
): Promise<{ url: string; voiceName: string; durationSec: number }> {
  const res = await fetch(`${baseUrl}/api/academy-library/generate-tts`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-academy-build-key': apiKey,
    },
    body: JSON.stringify({
      slug,
      language,
      // gender is required by the endpoint validator but ignored by the
      // ElevenLabs path — we always narrate with the A.S.T.R.A. female voice.
      gender: 'female',
      text,
      provider: 'elevenlabs',
    }),
  });
  const data = await res.json();
  if (!res.ok) {
    throw new Error(`HTTP ${res.status}: ${JSON.stringify(data)}`);
  }
  return data as { url: string; voiceName: string; durationSec: number };
}

async function main() {
  const opts = parseArgs();
  console.log('Encyclopedia TTS build');
  console.log('  baseUrl:', opts.baseUrl);
  console.log('  slug:', opts.slug ?? '(all)');

  const files = findLessonFiles().filter((f) => !opts.slug || f.includes(opts.slug));
  console.log(`Found ${files.length} lesson files`);

  const manifest = loadManifest();

  for (const file of files) {
    const lesson = await loadLesson(file);
    console.log(`\n[${lesson.slug}.${lesson.language}] ${lesson.title}`);

    const existing: LessonAssets = manifest[lesson.slug] ?? {
      images: {},
      audio: {
        uk: { female: '', male: '', durationSec: 0 },
        en: { female: '', male: '', durationSec: 0 },
      },
    };
    const audio = { ...(existing.audio ?? {}) } as LessonAssets['audio'];
    const lang: Language = lesson.language;
    const langAudio = audio[lang] ?? { female: '', male: '', durationSec: 0 };

    const text = buildSpokenText(lesson);
    console.log(`  text length: ${text.length} chars`);

    // Single A.S.T.R.A. narrator (female). The 'female' field stores the
    // ASTRA URL; 'male' is left empty — the player has no voice selector.
    if (!opts.force && langAudio.female) {
      console.log(`  ✓ audio ${lang} ASTRA (cached)`);
    } else {
      console.log(`  → audio ${lang} ASTRA ...`);
      try {
        const result = await callTtsEndpoint(opts.baseUrl, opts.apiKey, lesson.slug, lang, text);
        langAudio.female = result.url;
        langAudio.male = ''; // single-voice mode
        langAudio.durationSec = result.durationSec;
        console.log(`    ${result.url} (${result.durationSec}s, voice: ${result.voiceName})`);
      } catch (err) {
        console.error(`    FAILED: ${err instanceof Error ? err.message : String(err)}`);
      }
    }

    audio[lang] = langAudio;
    manifest[lesson.slug] = { ...existing, audio };
    saveManifest(manifest);
  }

  console.log(`\nDone. Manifest written to ${MANIFEST_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
