// Encyclopedia content types — Cosmic Academy v2 (Library / Енциклопедія).
//
// Lessons are authored as TypeScript modules so they get full type-checking,
// can co-exist with React components, and live next to the rendering code.
// Assets (images + TTS audio) are pre-generated by `scripts/encyclopedia-build.ts`
// and looked up at runtime via `assets-manifest.json` keyed by `cacheKey`.

export type Language = 'uk' | 'en';

export type SectionId =
  | 'astronomy'
  | 'astrophysics'
  | 'cosmology'
  | 'planetology'
  | 'astrobiology'
  | 'space-tech'
  | 'crewed-missions'
  | 'robotic-missions'
  | 'applied-space';

export type Difficulty = 'beginner' | 'intermediate' | 'advanced' | 'current2026';

export type AspectRatio = '16:9' | '9:16' | '4:3' | '3:4' | '1:1';

/** Inline illustration to be generated by Gemini at build time. */
export interface LessonImage {
  /** Stable identifier — same across uk/en for the same illustration. */
  cacheKey: string;
  /** Prompt for Gemini Imagen. May include `text on image` instructions. */
  prompt: string;
  alt: string;
  caption?: string;
  aspectRatio?: AspectRatio;
}

/** Inline hand-crafted SVG diagram (for schemes that AI can't draw reliably). */
export interface LessonDiagram {
  title: string;
  /** SVG markup string. Width="100%" advised. */
  svg: string;
  caption?: string;
}

/** A single section block of the lesson (heading + paragraphs + optional asset). */
export interface LessonBlock {
  /** If present, renders as h2 (level 2) or h3 (level 3) heading. */
  heading?: string;
  level?: 2 | 3;
  /** Markdown-lite paragraphs: `**bold**`, `_italic_` (renders as accent-cyan term). */
  paragraphs?: string[];
  image?: LessonImage;
  diagram?: LessonDiagram;
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correctIndex: number;
  explanation?: string;
}

export interface GlossaryTerm {
  term: string;
  definition: string;
}

export interface Source {
  title: string;
  url: string;
  /** e.g. "ApJL 2019, open access" */
  meta?: string;
}

/** Full lesson definition. One per language file. */
export interface Lesson {
  /** Stable slug — same across uk/en. */
  slug: string;
  language: Language;
  section: SectionId;
  /** Sort order within section. */
  order: number;
  difficulty: Difficulty;
  /** Estimated reading time in minutes. */
  readingTimeMin: number;
  title: string;
  /** One-line subtitle shown under the title. */
  subtitle: string;
  /** Hero image at the top of the lesson. */
  hero: LessonImage;
  /** Body — interleaves headings, paragraphs, images, and diagrams. */
  body: LessonBlock[];
  glossary: GlossaryTerm[];
  quiz: QuizQuestion[];
  sources: Source[];
  /** YYYY-MM-DD — date of last fact-check. */
  lastVerified: string;
}

/** Section meta — used in the encyclopedia table of contents. */
export interface SectionMeta {
  id: SectionId;
  /** Localized title, keyed by language. */
  title: Record<Language, string>;
  /** Localized one-line description. */
  description: Record<Language, string>;
}

// ────────────────────────────────────────────────────────────────────────────
// Asset manifest — populated by build script, embedded at compile time.
// ────────────────────────────────────────────────────────────────────────────

export interface LessonAudioAssets {
  /** Female narrator MP3 URL (Vercel Blob). */
  female: string;
  /** Male narrator MP3 URL (Vercel Blob). */
  male: string;
  /** Audio duration in seconds (rounded). */
  durationSec: number;
}

export interface LessonAssets {
  /** Map of cacheKey → image URL (Vercel Blob). Includes hero. */
  images: Record<string, string>;
  /** Audio URLs by language. */
  audio: Record<Language, LessonAudioAssets>;
}

/** The whole assets manifest is a map of slug → assets. */
export type AssetsManifest = Record<string, LessonAssets>;
